config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do
  	resources :comments, only: [:create]
  	member do 
  		post 'vote'
  	end
  end


  resources :comments do
  	member do
  		post 'vote'
  	end
  end

  resources :categories
  resources :users, only: [:show, :create, :edit, :update]


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence:true, length:{minimum: 5}
 
end

app/models/comment.rb
class Comment < ActiveRecord::Base;
	belongs_to :user
	belongs_to :post
	has_many :votes, as: :voteable
	validates :body, presence: :true, length: {minimum:5}


	def total_votes
		up_votes - down_votes
	end

	def up_votes
		self.votes.where(vote: true).size
	end

	def down_votes
		self.votes.where(vote: false).size
	end
end

app/models/post.rb
class Post < ActiveRecord::Base;
	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
	has_many :votes, as: :voteable


	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true

	def total_votes
		up_votes - down_votes
	end

	def up_votes
		self.votes.where(vote: true).size
	end

	def down_votes
		self.votes.where(vote: false).size
	end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base;
	has_many :posts 
	has_many :comments
	has_many :votes

	has_secure_password validations: false
	validates :username, presence: :true, uniqueness: :true
	validates :password, presence: :true, confirmation: :true, length: {minimum: 6}, on: :create
	validates :password_confirmation, presence: :true, on: :create

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :voteable, polymorphic: true

	validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
		current_user ||= User.find_by id: session[:user_id] 
  end

   def logged_in?
		!!current_user
   end


  def require_user
  	unless logged_in?
  		flash[:notice] = "You need to be logged in to do that"
  		redirect_to posts_path
  	end
  end

  def require_same_user
  	unless current_user == @post.user
  		flash[:error] = "You can't do that!"
  		redirect_to root_path
  	end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :require_user, only: [:new, :create]
	def index
		@category = Category.all
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
	end

	def create
		@category = Category.new(catparams)

		if @category.save
			flash[:notice] = "Category created"
			redirect_to root_path
		else
			render 'new'
		end
	end

	
	

	private
	def catparams

		params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_user

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(params.require(:comment).permit(:body))
		@comment.user = current_user

		if @comment.save
			flash[:notice] = "Your comment has been saved!"
			redirect_to post_path(@post)
		else
			render "posts/show"
		end
	end

	def vote
	if Vote.where(voteable_type: "Comment", user_id: current_user.id, voteable_id: params[:commentid]).empty?
	
		vote = Vote.create(vote: params[:vote], voteable_type: "Comment", voteable_id: params[:commentid], user_id: current_user.id)

		if vote.save
			flash[:notice] = "Your vote has been registered"
			redirect_to :back
		else
			flash[:error] = "There was an error"
			redirect_to :back
		end
	else
		flash[:error] = "You have already voted on this"
		redirect_to :back
	end

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]

  def index
  	@posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
  	@comment = Comment.new

  end

  def new
  	@post = Post.new

  end

  def create
  	@post = Post.new(myparams)
  	@post.creator = current_user

  	if @post.save
  		flash[:success] = "You have saved successfully!"
  		redirect_to posts_path
  	else
  		
     	render 'new'
  	end

  end

  def edit

  end

  def update

	  	
  	@post.update(myparams)

  	if @post.save
  		flash[:success] = "You have updated successfully!"
  		redirect_to post_path(@post)
  	else
  		render 'edit'
  	end
  end

  def vote
  	if Vote.where(voteable_type: "Post", user_id: current_user.id, voteable_id: params[:id]).empty?

	 	vote = Vote.create(vote: params[:vote], voteable_type: "Post", voteable_id: params[:id], user_id: current_user.id)
	 	if vote.save
	 		flash[:notice] = "Your vote was recorded"
	 		redirect_to :back
	 	else
	 		flash[:error] = "Your vote was not recorded"
	 		redirect_to :back
	 	end
	 else
	 	flash[:notice] = "You have already voted on this"
	 	redirect_to :back
	 end
  end


  private
  def myparams
  	params.require(:post).permit(:title, :description, :url, category_ids:[])
  end

  def set_post
  	@post = Post.find(params[:id])
  end	

   def require_same_user

  	unless current_user == @post.creator
  		flash[:error] = "You can't do that!"
  		redirect_to root_path
  	end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
	
		user = User.find_by username: (params[:username])
	
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id 
			flash[:success] = "You are now logged in"
			redirect_to posts_path
		else
			flash[:notice] = "Your username or password is wrong"
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(userparams)

		if @user.save
			flash[:notice] = "You have successfully registered"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render "new"
		end			
	end

	def show
		
		@user = User.find_by(params[:id])
	end

	def edit
		@user = User.find_by(params[:id])
	end

	def update
		@user = User.find_by(params[:id])
		@user.update(userparams)

		if @user.save
			flash[:notice] = "Updated successfully!"
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end



	private

	def userparams
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def make_http(url)
		url.starts_with?("http://") ? url : url = "http://#{url}"
	end

	def betterdatetime(datetime)
		datetime.strftime("%m/%d/%Y 1:%M%P %Z")
	end

	

	
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
<ul>
<% @category.errors.full_messages each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
<% end %>


<%= form_for @category do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Edit category" %>
<% end %>

app/views/categories/index.html.erb
<h2>Here's the list of all the Categories</h2>
<ul>
<% @category.each do |category| %>
  <li><%= category.name %> <%= link_to '[edit]', edit_category_path(category) %>
  </li>
<% end %>
<%= link_to "Create new Category", new_category_path %>

app/views/categories/new.html.erb
<%= render 'shared/errors', myclass: @category %>

<%= form_for @category do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Create category" %>
<% end %>

app/views/categories/show.html.erb
<h2>Category : <%= @category.name %>
<% @category.posts.each do |post| %>
<h4><%= post.title %></h4>
<p><%= post.description %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, class: 'brand' %>
  </li>
</ul>

<div class='btn-group nav_item'>
	 <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
	 Categories <span class="caret"></span>
		<% end %>
	 <ul class="dropdown-menu">
	    <% Category.all.each do |catname| %>
	    <li><%= link_to catname.name, category_path(catname) %></li>
	    <% end %>
	    <% if logged_in? %>
	    <li><%= link_to "+ New Category", new_category_path %>
	    <% end %>
	 </ul>
</div>

<% if logged_in? %>
	<div class='nav_item'>
		You are logged in as <%= current_user.username %>
	<div class='nav_item btn btn-warning'>
		<%= link_to 'New Post', new_post_path %>
	</div>
	<div class='btn-group nav_item'>
			 <%= link_to '', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %><%= current_user.username %><span class="caret"></span>
		<ul class="dropdown-menu">
			<li><%= link_to edit_user_path(current_user) do %>
				<i class="icon-pencil"></i>
				Edit profile
				<% end %>
			</li>
			<li><%= link_to user_path(current_user) do %>
				<i class="icon-user"></i>
				View profile
			<% end %>

			</li>
			<li><%= link_to logout_path do %>
				<i class="icon-star"></i>
				Logout
			<% end %>
			</li>
		</ul>
		<% end %>
	</div>


<% else %>
	
	<div class='nav_item'>
		<%= link_to 'Register', register_path %>
	</div>


	<div class='nav_item'>
		<%= link_to 'Login', login_path %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit post' %>
<%= render 'shared/postform' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All posts' %>
<%= render 'shared/showposts', obj: @posts %>

<%= link_to 'Create a new post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'shared/errors', myclass: @post %>
<%= render 'shared/postform' %>

app/views/posts/show.html.erb
<%= render 'shared/content_title', title: 'Showing posts' %>
<div class="well">
	<h3><%= @post.title %></h3>
	<p><%= @post.description %>
	<p><%= link_to make_http(@post.url), make_http(@post.url) %></p>
	<p>[<%= link_to 'Edit this post', edit_post_path(@post) %>]</p>
</div>

<p>Comments:</p>
<ul>

<%= render 'shared/comments', obj: @post, show_post: false %>	



<% if logged_in? %>

	<%= render 'shared/errors', myclass: @comment %>
	<%= form_for [@post, @comment] do |f| %>
		<%= f.label "Comments" %>
		<%= f.text_area :body %>
		<p><%= f.submit "Create comment" %></p>
	<% end %>
<% end %>

app/views/shared/_comments.html.erb
<% obj.comments.each do |comment| %>
<div class="span0 well">
	<% if logged_in? %> 
		<%= link_to vote_comment_path(comment, vote: true, commentid: comment.id), method: "post" do %>
		<i class="icon-circle-arrow-up"></i>
		<% end %>
	<% end %>
<br/>
<%= "#{comment.total_votes} votes" %>
<br/>
	<% if logged_in? %> 
		<%= link_to vote_comment_path(comment, vote: false, commentid: comment.id), method: "post" do %>
		<i class="icon-circle-arrow-down"></i>
		<% end %>
	<% end %>
</div>

<div class="well">
	<p><%= comment.body %> 
	<% if show_post == true %>
	on <%= link_to comment.post.title, post_path(comment.post) %>
	<% end %>
	</p>
	<div class="quiet">by <%=link_to comment.user.username, user_path(comment.user) %> at <%= betterdatetime(comment.created_at) %></div>
</div>
<% end %>

app/views/shared/_content_title.html.erb
<h2><%= title %></h2>

app/views/shared/_errors.html.erb
<% if myclass.errors.any? %>
<div class = "alert alert-error">
<p>Please fix the errors : </p>
<ul>
<% myclass.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
<% end %>
</div>

app/views/shared/_postform.html.erb
<%= render 'shared/errors', :myclass => @post %>


<%= form_for @post do |f| %>
	<div class="control-group">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="control-group">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="control-group">
		<%= f.label :url %>
		<%= f.text_field :url %>


	<div class="control-group">
		<%= f.label "Categories:" %>
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
  		<% b.label(class: "checkbox inline") { b.check_box(class: "checkbox") + b.text } %>
		<% end %>
	</div>

		<%= f.submit(@post.new_record? ? 'Create post' : 'Update post', class: "btn btn-primary") %>

</div>
<% end %>

app/views/shared/_showposts.html.erb
<% obj.each do |post| %>
<div class="span2 well text-center">
	<% if logged_in? %>
		<%= link_to vote_post_path(post, vote: true), method: "post" do %>
		<i class="icon-circle-arrow-up"></i>
		<% end %>
	<% end %>

	<br/>
	<%= "#{post.total_votes} votes" %>
	<br/>

	<% if logged_in? %>
		<%= link_to vote_post_path(post, vote: false), method: "post" do %>
		<i class="icon-circle-arrow-down"></i>
		<% end %>
	<% end %>
</div>

<div class="span8 well">
	<h3><%= link_to post.title, post_path(post) %></h3>
	<%= render post.categories %></p>
	<p><%= post.description %></p>

	<p class="quiet">Posted by <%= post.creator.username %> at <%= betterdatetime(post.created_at) %> 
	</p>
	<% commentssize = "#{post.comments.size} comments" %>
	<p><%= link_to commentssize, post_path(post) %>   <%= if logged_in?; link_to 'Edit', edit_post_path(post); end  %><p>
</div>
	
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render 'shared/errors', :myclass => @user %>

	<%= form_for @user do |f| %>
	<div class="Control-group">
		<%= f.label :username, "Username" %>
		<%= f.text_field :username %>
	<div class="Control-group">
		<%= f.label :password, "Password" %>
		<%= f.password_field :password %>
	</div>

	<%= f.submit "Update profile", class: "btn btn-success" %>
	<% end %>

app/views/users/new.html.erb
<h2> Registration </h2>
<%= render 'shared/errors', myclass: @user %>
<%= form_for @user do |f| %>
<div class="control-group">
	<%= f.label :username, "Choose a Username" %>
	<%= f.text_field :username %>
</div>

<div class="control-group">
	<%= f.label :password, "Choose a Password" %>
	<%= f.password_field :password %>
</div>

<div class="control-group">
	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation %>
</div>

<%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<h3>Profile: <%= @user.username %></h3>
<hr>
<div class="well">
	<h4>Username: <%= @user.username %></h4>
	<h4>Timezone: </h4>
</div>


<div>
	<h2><%= @user.username %>'s Activity</h2>
</div>

<ul class="nav nav-tabs">
	<li class="<%= 'active' if params[:tab].nil? %> "><%= link_to "Posts (#{@user.posts.size})", user_path(@user) %></li>

	<li class="<%= 'active' if params[:tab] == 'comments' %> "><%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %></li>
</ul>

<% if params[:tab].nil? %>
	<%= render 'shared/showposts', obj: @user.posts %>
<% else %>
	<%= render 'shared/comments', obj: @user, show_post: true %>
<% end %>